name: cap1
channels:
  - nvidia
  - pytorch
dependencies:
  - pytorch>=1.6.0, <2.0.0
  - torchvision
  - torchaudio
  - cudatoolkit
  - numpy
  - scipy
  - pyyaml
  - torchvision
  - tqdm
  - scikit-learn