
# define partitions for your network
bn_partitions:
    - 5
    - 5
    - 5
    - 5
    - 5
partitions:
    conv1.weight:
        5
    layer1.0.conv1.weight:
        5
    layer1.0.conv2.weight:
        5
    layer2.0.conv1.weight:
        5
    layer2.0.conv2.weight:
        5
    layer3.0.conv1.weight:
        5
    layer3.0.conv2.weight:
        5
    layer4.0.conv1.weight:
        5
    layer4.0.conv2.weight:
        5
    hidden1.weight:
        5
    hidden2.weight:
        5
    hidden3.weight:
        5
   