
# define partitions for your network
bn_partitions:
    - 1
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
partitions:
   conv1.weight:
     1
   layer1.0.conv1.weight:
     4
   layer1.0.conv2.weight:
     4
   layer1.1.conv1.weight:
     4
   layer1.1.conv2.weight:
     4
   layer2.0.conv1.weight:
     4
   layer2.0.conv2.weight:
     4
   layer2.0.shortcut.0.weight:
     4
   layer2.1.conv1.weight:
     4
   layer2.1.conv2.weight:
     4
   layer3.0.conv1.weight:
     4
   layer3.0.conv2.weight:
     4
   layer3.0.shortcut.0.weight:
     4
   layer3.1.conv1.weight:
     4
   layer3.1.conv2.weight:
     4
   layer4.0.conv1.weight:
     4
   layer4.0.conv2.weight:
     4
   layer4.0.shortcut.0.weight:
     4
   layer4.1.conv1.weight:
     4
   layer4.1.conv2.weight:
     4

   