
# define partitions for your network
bn_partitions:
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
partitions:
   conv1.weight:
     1
   'block1.layer.0.conv1.weight': 2
   'block1.layer.0.conv2.weight': 2
   'block1.layer.0.convShortcut.weight': 2
   'block1.layer.1.conv1.weight': 2
   'block1.layer.1.conv2.weight': 2
   'block1.layer.2.conv1.weight': 2
   'block1.layer.2.conv2.weight': 2
   'block1.layer.3.conv1.weight': 2
   'block1.layer.3.conv2.weight': 2
   'block2.layer.0.conv1.weight': 2
   'block2.layer.0.conv2.weight': 2
   'block2.layer.0.convShortcut.weight': 2
   'block2.layer.1.conv1.weight': 2
   'block2.layer.1.conv2.weight': 2
   'block2.layer.2.conv1.weight': 2
   'block2.layer.2.conv2.weight': 2
   'block2.layer.3.conv1.weight': 2
   'block2.layer.3.conv2.weight': 2
   'block3.layer.0.conv1.weight': 2
   'block3.layer.0.conv2.weight': 2
   'block3.layer.0.convShortcut.weight': 2
   'block3.layer.1.conv1.weight': 2
   'block3.layer.1.conv2.weight': 2
   'block3.layer.2.conv1.weight': 2
   'block3.layer.2.conv2.weight': 2
   'block3.layer.3.conv1.weight': 2
   'block3.layer.3.conv2.weight': 2

   