
# define partitions for your network
bn_partitions:
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
partitions:
   conv1.weight:
     1
   'block1.layer.0.conv1.weight': 8
   'block1.layer.0.conv2.weight': 8
   'block1.layer.0.convShortcut.weight': 8
   'block1.layer.1.conv1.weight': 8
   'block1.layer.1.conv2.weight': 8
   'block1.layer.2.conv1.weight': 8
   'block1.layer.2.conv2.weight': 8
   'block1.layer.3.conv1.weight': 8
   'block1.layer.3.conv2.weight': 8
   'block2.layer.0.conv1.weight': 8
   'block2.layer.0.conv2.weight': 8
   'block2.layer.0.convShortcut.weight': 8
   'block2.layer.1.conv1.weight': 8
   'block2.layer.1.conv2.weight': 8
   'block2.layer.2.conv1.weight': 8
   'block2.layer.2.conv2.weight': 8
   'block2.layer.3.conv1.weight': 8
   'block2.layer.3.conv2.weight': 8
   'block3.layer.0.conv1.weight': 8
   'block3.layer.0.conv2.weight': 8
   'block3.layer.0.convShortcut.weight': 8
   'block3.layer.1.conv1.weight': 8
   'block3.layer.1.conv2.weight': 8
   'block3.layer.2.conv1.weight': 8
   'block3.layer.2.conv2.weight': 8
   'block3.layer.3.conv1.weight': 8
   'block3.layer.3.conv2.weight': 8

   